// Domain project pools for auto-assignment
const DOMAIN_PROJECT_POOLS = {
  "data science": {
    simple: [{"title": "COVID-19 India State Analysis", "tech": "Python, Pandas, Plotly, Geopandas", "desc": "State-level case/death/recovery data, choropleth map, peak identification."}, {"title": "Netflix Content EDA", "tech": "Python, Pandas, Seaborn, Matplotlib", "desc": "Genre distribution, country treemap, release-year trend analysis."}, {"title": "World Population Growth Study", "tech": "Python, Pandas, Plotly", "desc": "UN population data, country growth rate chart, 2050 projection."}, {"title": "IPL Cricket Data Analysis", "tech": "Python, Pandas, Plotly, Streamlit", "desc": "Ball-by-ball data, player strike rate, team win%, venue run-rate."}, {"title": "Titanic Survival EDA", "tech": "Python, Pandas, Seaborn, Matplotlib", "desc": "Passenger survival factors, age/class/gender breakdown."}, {"title": "Zomato Restaurant EDA", "tech": "Python, Pandas, Plotly, Streamlit", "desc": "Restaurant ratings, cuisine trends, price analysis by city."}],
    medium: [{"title": "Indian Stock Market EDA & Forecast", "tech": "Python, Pandas, yfinance, Prophet, Plotly", "desc": "NSE multi-stock OHLCV, 30-day forecast, sector performance comparison."}, {"title": "Crime Pattern Analysis Dashboard", "tech": "Python, Pandas, Folium, Plotly, Streamlit", "desc": "City crime dataset, type/time/location EDA, monthly trend, hotspot map."}, {"title": "Air Quality Index India EDA", "tech": "Python, Pandas, Plotly, Geopandas", "desc": "AQI data across cities, pollutant trend, seasonal pattern analysis."}, {"title": "Startup Ecosystem India Report", "tech": "Python, Pandas, Plotly, NetworkX", "desc": "Funding + sector data, investor network graph, city startup map."}, {"title": "Healthcare Cost Driver Analysis", "tech": "Python, Pandas, Plotly, Scikit-learn", "desc": "Insurance + hospital cost data, driver regression, cost by diagnosis."}, {"title": "Electric Vehicle Adoption Analysis", "tech": "Python, Pandas, Plotly, Geopandas", "desc": "EV registration data, state-wise adoption, charging infra correlation."}],
    hard:   [{"title": "Social Mobility & Income Inequality Study", "tech": "Python, Pandas, Plotly, Geopandas, Scikit-learn", "desc": "World Bank + OECD data, Gini index trend, mobility predictor, interactive report."}, {"title": "Smart City Sensor Data Analysis", "tech": "Python, Pandas, Plotly, Folium, Prophet", "desc": "IoT sensor dataset (air/noise/traffic), anomaly detection, zone comparison, forecast."}, {"title": "NLP-Powered Financial Report Analyzer", "tech": "Python, spaCy, Gensim, Plotly, Streamlit", "desc": "Scrape annual report PDFs, topic extraction, sentiment trend, KPI comparison."}, {"title": "Predictive Population Health Dashboard", "tech": "Python, Pandas, Scikit-learn, Prophet, Plotly", "desc": "District health data, disease burden forecast, risk stratification, intervention planner."}, {"title": "Geospatial Urban Sprawl Study", "tech": "Python, Geopandas, OSMnx, Folium, Plotly", "desc": "Satellite-derived urban boundary data, expansion rate, green cover loss, 3-city compare."}, {"title": "Agricultural Market Price Analyzer", "tech": "Python, Pandas, Plotly, Prophet, Streamlit", "desc": "APMC mandi price data, crop price forecast, seasonal trend, district comparison."}],
  },
  "machine learning": {
    simple: [{"title": "Iris Flower Species Classifier", "tech": "Python, Scikit-learn, Pandas, Matplotlib", "desc": "Logistic Regression on Iris dataset, confusion matrix, species predictor UI."}, {"title": "Diabetes Risk Predictor", "tech": "Python, Scikit-learn, Pandas, Streamlit", "desc": "Logistic Regression on Pima dataset, patient form, recall-optimized threshold."}, {"title": "Boston Housing Price Estimator", "tech": "Python, Scikit-learn, Pandas, Matplotlib", "desc": "Linear/Ridge regression, RMSE/R\u00b2, residual plot, feature coefficient chart."}, {"title": "Titanic Survival Predictor", "tech": "Python, Pandas, Scikit-learn, Streamlit", "desc": "Binary classification, feature engineering, ROC curve, Streamlit input form."}, {"title": "Wine Quality Classifier", "tech": "Python, Scikit-learn, Pandas, Seaborn", "desc": "Multi-class RF on UCI Wine, accuracy comparison, feature importance chart."}, {"title": "Spam SMS Detector", "tech": "Python, NLTK, Naive Bayes, Streamlit", "desc": "TF-IDF on SMS Spam Collection, ROC curve, live message tester."}],
    medium: [{"title": "Crop Yield Prediction System", "tech": "Python, XGBoost, Pandas, Streamlit", "desc": "Regression on crop dataset, soil+weather inputs, district-level yield map."}, {"title": "House Rent Price Predictor", "tech": "Python, XGBoost, Pandas, Streamlit", "desc": "Feature engineering on rental dataset, neighborhood filter, rent estimator."}, {"title": "Road Traffic Volume Predictor", "tech": "Python, Scikit-learn, Pandas, Folium", "desc": "Traffic dataset, time + weather features, city intersection heatmap."}, {"title": "Twitter Sentiment Dashboard", "tech": "Python, Tweepy, TextBlob, Plotly, Streamlit", "desc": "Real-time tweet sentiment, trending keyword cloud, sentiment timeline."}, {"title": "Electricity Consumption Predictor", "tech": "Python, Prophet, Pandas, Streamlit", "desc": "Household power dataset, daily consumption forecast, anomaly flagging."}, {"title": "Fake Job Posting Detector", "tech": "Python, NLTK, TF-IDF, Scikit-learn, Streamlit", "desc": "Binary NLP classifier on EMSCAD dataset, keyword explainability."}],
    hard:   [{"title": "Real-Time Pose Estimation Trainer", "tech": "Python, MediaPipe, TensorFlow, Flask, Socket.io", "desc": "Live webcam pose detection, rep counter for exercises, form feedback API."}, {"title": "AI-Powered Resume Parser & Ranker", "tech": "Python, spaCy, BERT, FastAPI, React", "desc": "Batch resume upload, JD matching, ranked shortlist, skills gap PDF report."}, {"title": "Sign Language to Text Converter", "tech": "Python, MediaPipe, LSTM, TensorFlow, Gradio", "desc": "Real-time hand gesture capture, sequence-to-text decoder, accuracy chart."}, {"title": "Predictive Maintenance System", "tech": "Python, Scikit-learn, Pandas, Plotly, Streamlit", "desc": "Sensor time-series, failure prediction, maintenance schedule optimizer."}, {"title": "Sarcasm Detection in Social Media", "tech": "Python, RoBERTa HuggingFace, FastAPI, React", "desc": "Fine-tune on Reddit sarcasm dataset, confidence score, batch CSV API."}, {"title": "Driver Drowsiness Detection System", "tech": "Python, OpenCV, MediaPipe, Keras, Flask", "desc": "Real-time eye/face detection, drowsiness alert system, video feed demo."}],
  },
  "artificial intelligence": {
    simple: [{"title": "Keyword-Based FAQ Chatbot", "tech": "Python, NLTK, Flask, Bootstrap", "desc": "Intent matching on custom FAQ dataset, response retrieval, multi-turn conversation log."}, {"title": "AI Text Summarizer Tool", "tech": "Python, HuggingFace BART, Streamlit", "desc": "Paste article \u2192 abstractive summary, length slider, copy button."}, {"title": "AI Quote & Motivation Generator", "tech": "Python, Gemini API, Flask, Bootstrap", "desc": "Topic input, AI generates 5 quotes, mood filter, save-to-favourites."}, {"title": "AI Recipe Generator from Ingredients", "tech": "Python, Gemini API, Streamlit", "desc": "Enter available ingredients, AI suggests 3 recipes with steps, dietary filter."}, {"title": "AI Grammar Correction Assistant", "tech": "Python, LanguageTool API, Flask, React", "desc": "Text input, error highlighting, corrected output, confidence color-code."}, {"title": "AI Joke & Story Generator", "tech": "Python, Gemini API, Streamlit", "desc": "Genre/mood selector, AI-generated jokes or short stories, regenerate button."}],
    medium: [{"title": "AI Interview Question Generator", "tech": "Python, Gemini API, FastAPI, React", "desc": "Upload JD/resume, generate role-specific questions by difficulty, PDF export."}, {"title": "AI Product Description Writer", "tech": "Python, Gemini API, FastAPI, React", "desc": "Enter product name + features, generate 3 tone-varied descriptions, SEO score."}, {"title": "Conversational Language Tutor", "tech": "Python, Gemini API, Flask, Bootstrap", "desc": "Choose language + level, AI conducts lesson, grammar correction, vocab quiz."}, {"title": "AI Document Classifier", "tech": "Python, spaCy, BERT, FastAPI", "desc": "Multi-class document type tagger (invoice/contract/report), confidence, batch CSV API."}, {"title": "Agentic Research Assistant", "tech": "Python, LangChain, DuckDuckGo Tool, Streamlit", "desc": "Input research topic, agent searches + summarizes web sources, cited report."}, {"title": "AI Meeting Minutes Generator", "tech": "Python, Whisper ASR, Gemini API, Streamlit", "desc": "Upload audio recording, transcription, action items extraction, summary PDF."}],
    hard:   [{"title": "Multi-Agent Task Automation System", "tech": "Python, LangChain Agents, FastAPI, React", "desc": "Planner + executor agents, multi-step task decomposition, tool use (search/code/file)."}, {"title": "RAG Chatbot on Custom Knowledge Base", "tech": "Python, LangChain, ChromaDB, Gemini API, Streamlit", "desc": "Multi-PDF ingestion, vector embeddings, semantic search, source citation, multi-turn."}, {"title": "AI Legal Contract Analyzer", "tech": "Python, GPT-4o/Gemini, LangChain, Streamlit", "desc": "Upload contract PDF, clause extraction, risk flagging, plain-English summary."}, {"title": "AI-Powered Mock Interview Coach", "tech": "Python, Whisper ASR, Gemini API, React, Flask", "desc": "Voice-based interview, speech-to-text, AI follow-up questions, answer scoring, report."}, {"title": "Autonomous Data Analysis Agent", "tech": "Python, LangChain, Pandas, Streamlit", "desc": "Upload CSV, agent auto-detects columns, runs EDA, generates insights report."}, {"title": "AI Video Scene Describer", "tech": "Python, CLIP HuggingFace, OpenCV, FastAPI", "desc": "Upload video, keyframe extraction, CLIP caption per scene, narrative summary."}],
  },
  "full stack development": {
    simple: [{"title": "Personal Task Manager App", "tech": "React.js, Node.js, MySQL, JWT", "desc": "Task CRUD, priority tags, due-date filter, completion toggle, user auth."}, {"title": "Notes & Bookmarks Web App", "tech": "React.js, Express, MongoDB, JWT", "desc": "Create/edit/delete notes, tag system, URL bookmark saver, search filter."}, {"title": "Contact Directory App", "tech": "React.js, Node.js, PostgreSQL, JWT", "desc": "CRUD contacts, search/filter, import CSV, profile photos, dark mode."}, {"title": "Simple Blog Platform", "tech": "React.js, Node.js, MongoDB, JWT", "desc": "Create/edit posts, markdown editor, tags, comments, user profiles."}, {"title": "Recipe Book Web App", "tech": "React.js, Express, MongoDB", "desc": "Add/search recipes, ingredient list, step-by-step cooking mode, favorites."}, {"title": "Poll & Voting App", "tech": "React.js, Node.js, PostgreSQL, Socket.io", "desc": "Create polls, real-time vote count, results chart, expiry timer."}],
    medium: [{"title": "Job Application Tracker", "tech": "React.js, Node.js, PostgreSQL, Chart.js, JWT", "desc": "Track applications by status, Kanban view, deadline alerts, stats dashboard."}, {"title": "Online Quiz Platform", "tech": "React.js, Node.js, MongoDB, Socket.io", "desc": "Question bank, timed quiz, live leaderboard, auto-grade, result analytics."}, {"title": "Budget Tracking Web App", "tech": "React.js, Node.js, PostgreSQL, Chart.js", "desc": "Income/expense CRUD, category budgets, monthly trend chart, PDF report."}, {"title": "Student Attendance Management", "tech": "React.js, Node.js, MySQL, JWT, Chart.js", "desc": "QR code check-in, absent alerts, attendance report, teacher dashboard."}, {"title": "Expense Split App", "tech": "React.js, Node.js, MongoDB, Socket.io", "desc": "Group expenses, auto-split, settle-up tracker, real-time balance update."}, {"title": "College Event Management System", "tech": "React.js, Node.js, PostgreSQL, Cloudinary", "desc": "Event CRUD, registration, seat booking, QR ticket, attendance report."}],
    hard:   [{"title": "Multi-Tenant Project Management SaaS", "tech": "React.js, Node.js, PostgreSQL, Socket.io, Stripe", "desc": "Org/workspace/board/card CRUD, real-time updates, role access, Stripe billing."}, {"title": "E-Learning Platform with Certificates", "tech": "React.js, Node.js, MongoDB, Cloudinary, Stripe", "desc": "Course builder, video streaming, quiz engine, progress tracking, PDF cert generator."}, {"title": "Healthcare Appointment System", "tech": "React.js, Node.js, PostgreSQL, Socket.io, Nodemailer", "desc": "Doctor/patient portal, slot booking, video consult, prescription PDF, reminders."}, {"title": "Real-Time Online Auction Platform", "tech": "React.js, Node.js, PostgreSQL, Socket.io, Stripe", "desc": "Live bidding, countdown timer, auto-outbid, payment, seller dashboard."}, {"title": "Freelance Marketplace Platform", "tech": "React.js, Node.js, PostgreSQL, Stripe, Socket.io", "desc": "Gig listing, proposal system, escrow payment, review/rating, chat."}, {"title": "Corporate HR & Payroll System", "tech": "React.js, Node.js, PostgreSQL, PDFKit, JWT", "desc": "Employee CRUD, leave management, payroll calculator, payslip PDF, role access."}],
  },
  "data analyst": {
    simple: [{"title": "Superstore Sales Performance Report", "tech": "Python, Pandas, Plotly, Power BI", "desc": "Kaggle Superstore data, regional KPIs, top-product bar chart, manager summary PDF."}, {"title": "HR Headcount & Turnover Dashboard", "tech": "Python, Pandas, Seaborn, Matplotlib", "desc": "Employee dataset, dept headcount, attrition rate chart, YoY trend."}, {"title": "E-Commerce Return Rate Analyzer", "tech": "Python, Pandas, Plotly, Streamlit", "desc": "Returns dataset, reason categorization, SKU-level return rate, seller report."}, {"title": "Website Traffic Analytics Dashboard", "tech": "Python, Pandas, Plotly, Streamlit", "desc": "GA export data, session/bounce/conversion trend, channel breakdown."}, {"title": "Attendance & Punctuality Tracker", "tech": "Python, Pandas, Openpyxl, Plotly", "desc": "Employee check-in data, late arrival pattern, dept comparison, monthly PDF."}, {"title": "Monthly Revenue Trend Analyzer", "tech": "Python, Pandas, Plotly, Power BI", "desc": "Revenue CSV, MoM growth, product mix chart, top-10 customers."}],
    medium: [{"title": "Retail Store Footfall Insights", "tech": "Python, Pandas, Plotly, Power BI", "desc": "Hourly footfall + sales data, peak-hour analysis, conversion rate, staff optimizer."}, {"title": "Product Profitability Analysis", "tech": "Python, Pandas, Plotly, Seaborn", "desc": "Revenue \u2013 COGS model, margin by SKU/category, waterfall P&L chart, pricing levers."}, {"title": "Customer Cohort Retention Dashboard", "tech": "Python, Pandas, Plotly, Streamlit", "desc": "Monthly cohort table, retention heatmap, churn inflection finder, segment filter."}, {"title": "Ad Spend Attribution Analyzer", "tech": "Python, Pandas, Plotly, Streamlit", "desc": "Multi-channel ad data, ROAS by channel, attribution model comparison."}, {"title": "Inventory Turnover Analysis", "tech": "Python, Pandas, Plotly, Openpyxl", "desc": "Stock movement data, turnover ratio, slow-mover alert, reorder point calculator."}, {"title": "Employee Productivity Score Card", "tech": "Python, Pandas, Plotly, Streamlit", "desc": "Task completion, quality score, peer review data, monthly performance card."}],
    hard:   [{"title": "Real-Time Sales Command Center", "tech": "Python, Pandas, Streamlit, Plotly, SQL", "desc": "Live DB connection, auto-refreshing KPI tiles, drill-down by region/rep/product."}, {"title": "Predictive Churn Cohort Tracker", "tech": "Python, Pandas, Scikit-learn, Plotly, Power BI", "desc": "Cohort CLV + ML churn risk, early-warning segment filter, retention action log."}, {"title": "Multi-Source Data Pipeline Dashboard", "tech": "Python, Pandas, SQLAlchemy, Plotly, Airflow", "desc": "ETL from 3 sources (CSV, API, DB), unified dashboard, scheduled refresh."}, {"title": "HR Analytics & Workforce Planning Tool", "tech": "Python, Pandas, Plotly, Scikit-learn, Streamlit", "desc": "Headcount forecast, skill gap analysis, succession planning matrix, org chart."}, {"title": "Omnichannel Sales Attribution Dashboard", "tech": "Python, Pandas, Plotly, SQL, Streamlit", "desc": "Online + offline sales merge, touchpoint attribution, ROAS by channel, exec report."}, {"title": "Financial Risk Exposure Dashboard", "tech": "Python, Pandas, Plotly, Scikit-learn", "desc": "Portfolio data, VaR calculation, stress test scenarios, risk heatmap."}],
  },
  "front end development": {
    simple: [{"title": "Personal Portfolio Website", "tech": "React.js, CSS3, EmailJS", "desc": "Animated hero, projects grid, skills bar, contact form, dark/light toggle."}, {"title": "Currency Converter App", "tech": "React.js, Exchange Rate API, Tailwind", "desc": "Real-time rates, 150+ currencies, swap button, conversion history."}, {"title": "BMI Calculator with Chart", "tech": "React.js, Chart.js, Tailwind CSS", "desc": "Height/weight input, BMI result, category indicator, trend line chart."}, {"title": "Age Calculator App", "tech": "React.js, date-fns, Tailwind CSS", "desc": "DOB input, exact age (years/months/days), next birthday countdown."}, {"title": "Pomodoro Productivity Timer", "tech": "React.js, Tailwind, Web Audio API", "desc": "25/5 min timer, custom intervals, session counter, break alarm sound."}, {"title": "Trivia Quiz Game", "tech": "React.js, Open Trivia API, Tailwind", "desc": "Category/difficulty selector, 10 questions, score tracker, leaderboard."}],
    medium: [{"title": "Job Board UI with Filters", "tech": "React.js, Tailwind CSS, Context API", "desc": "Job card listing, search + multi-filter, bookmark, pagination, skeleton loader."}, {"title": "Crypto Price Tracker Dashboard", "tech": "React.js, CoinGecko API, Chart.js, Tailwind", "desc": "Live prices, 7-day sparkline, portfolio tracker, price alert toggle."}, {"title": "Travel Itinerary Planner", "tech": "React.js, Google Maps API, Tailwind", "desc": "Trip builder, day-wise stops, map view, distance calculator, PDF export."}, {"title": "Music Player with Visualizer", "tech": "React.js, Web Audio API, Canvas, Tailwind", "desc": "Playlist CRUD, frequency visualizer, equalizer, waveform display."}, {"title": "Recipe Finder App", "tech": "React.js, Spoonacular API, Tailwind", "desc": "Ingredient-based search, dietary filter, nutrition info, save favorites."}, {"title": "Movie Recommendation App", "tech": "React.js, TMDB API, Tailwind, Redux", "desc": "Search/browse movies, genre filter, similar movies, watchlist, ratings."}],
    hard:   [{"title": "Real-Time Collaborative Notes App", "tech": "React.js, Socket.io, Tailwind, Quill.js", "desc": "Multi-user note editing, live cursor, undo/redo, room links, export PDF."}, {"title": "3D Interactive Portfolio", "tech": "React.js, Three.js, GSAP, Tailwind", "desc": "3D scene hero, scroll animations, project showcase, particle effects."}, {"title": "E-Commerce Frontend with Cart", "tech": "React.js, Redux, Stripe.js, Tailwind", "desc": "Product listing, filters, cart, checkout flow, order confirmation, wishlist."}, {"title": "Social Media Dashboard", "tech": "React.js, Socket.io, Redux, Tailwind", "desc": "Feed, stories, likes/comments real-time, notifications, dark mode."}, {"title": "Online Code Editor", "tech": "React.js, Monaco Editor, Tailwind, Piston API", "desc": "Multi-language support, syntax highlight, run code, share snippet, themes."}, {"title": "Kanban Project Board", "tech": "React.js, DnD-Kit, Socket.io, Tailwind", "desc": "Drag-drop cards, multi-board, real-time sync, labels, due dates, members."}],
  },
  "cloud computing": {
    simple: [{"title": "Static Site Hosting with CDN on AWS", "tech": "AWS S3, CloudFront, Route53", "desc": "Deploy React app to S3, CloudFront distribution, custom domain, SSL cert."}, {"title": "Serverless Image Resizer", "tech": "AWS Lambda, S3, API Gateway, Python", "desc": "Upload image \u2192 Lambda resizes to 3 sizes \u2192 S3 storage, presigned URL response."}, {"title": "Cloud File Storage App", "tech": "AWS S3, EC2, Node.js, React", "desc": "Upload/download/delete files via S3, file listing UI, file type filter."}, {"title": "Auto-Scaling Web Server", "tech": "AWS EC2, Auto Scaling, ALB, CloudWatch", "desc": "Launch template, scaling policy, health checks, load balancer, dashboard."}, {"title": "RDS MySQL Setup with Backups", "tech": "AWS RDS, EC2, MySQL, CloudWatch", "desc": "Multi-AZ RDS, automated backups, parameter group, monitoring alarms."}],
    medium: [{"title": "Containerized Microservices on AWS", "tech": "Docker, AWS ECS, ECR, ALB", "desc": "Dockerize 3 microservices, push to ECR, deploy via ECS Fargate, ALB routing."}, {"title": "CI/CD Pipeline with GitHub Actions", "tech": "GitHub Actions, AWS EC2, S3, CodeDeploy", "desc": "Push-to-deploy pipeline, staging + prod environments, rollback mechanism."}, {"title": "Cloud Cost Optimization Dashboard", "tech": "AWS Cost Explorer, Lambda, S3, QuickSight", "desc": "Daily cost report, unused resource detector, savings recommendation, PDF."}, {"title": "VPC with Public/Private Subnets", "tech": "AWS VPC, NAT Gateway, EC2, Security Groups", "desc": "3-tier VPC architecture, bastion host, NAT gateway, NACLs, flow logs."}, {"title": "Kubernetes Cluster on EKS", "tech": "AWS EKS, kubectl, Helm, CloudWatch", "desc": "EKS cluster setup, deploy sample app, HPA, ingress controller, monitoring."}, {"title": "CloudFormation Infrastructure Stack", "tech": "AWS CloudFormation, EC2, RDS, S3, SNS", "desc": "Full infra as code, nested stacks, parameters, outputs, change sets."}],
    hard:   [{"title": "Multi-Region Disaster Recovery Setup", "tech": "AWS Route53, RDS, S3, CloudFormation", "desc": "Active-passive DR, RDS cross-region replica, Route53 health-check failover."}, {"title": "Serverless Event-Driven Architecture", "tech": "AWS Lambda, SQS, SNS, DynamoDB, API Gateway", "desc": "Order processing pipeline, fan-out with SNS, dead-letter queue, CloudWatch."}, {"title": "Full CI/CD Pipeline with Kubernetes", "tech": "Jenkins, Docker, Kubernetes, AWS EKS, Helm", "desc": "Multi-stage pipeline, Docker build, Helm deploy to EKS, Slack notifications."}, {"title": "Data Lake on AWS", "tech": "AWS S3, Glue, Athena, QuickSight, Lambda", "desc": "Raw/curated/processed zones, Glue ETL jobs, Athena queries, BI dashboard."}, {"title": "ML Model Deployment on AWS", "tech": "AWS SageMaker, Lambda, API Gateway, S3", "desc": "Train model in SageMaker, deploy endpoint, REST API, A/B testing, monitoring."}, {"title": "Zero-Trust Security Architecture", "tech": "AWS IAM, Cognito, WAF, Shield, GuardDuty", "desc": "Identity-based access, MFA enforcement, WAF rules, threat detection, audit."}, {"title": "Hybrid Cloud with AWS Direct Connect", "tech": "AWS Direct Connect, VPN, Transit Gateway, VPC", "desc": "On-prem to AWS connectivity, BGP routing, failover VPN, latency testing."}],
  },
  "cyber security": {
    simple: [{"title": "Network Vulnerability Scanner", "tech": "Python, Nmap, Flask, Bootstrap", "desc": "Port scanning on local subnet, open-port risk rating, CVE lookup, HTML report."}, {"title": "Password Strength Analyzer", "tech": "Python, Flask, zxcvbn, React", "desc": "Strength scoring, crack-time estimate, secure password generator."}, {"title": "Phishing Email Detector", "tech": "Python, NLTK, Scikit-learn, Flask", "desc": "ML classifier on email dataset, phishing URL checker, confidence score."}, {"title": "File Integrity Monitor", "tech": "Python, hashlib, Flask, SQLite", "desc": "SHA-256 baseline, tamper detection, alert log, scheduled scan."}, {"title": "Basic Firewall Rules Simulator", "tech": "Python, iptables, Flask, Bootstrap", "desc": "Rule builder UI, traffic allow/block simulation, rule priority, log viewer."}],
    medium: [{"title": "Web Application Firewall (WAF) Tool", "tech": "Python, Flask, regex, SQLite", "desc": "XSS/SQLi pattern detection, request logging, block list management."}, {"title": "Security Audit Report Generator", "tech": "Python, OpenVAS, Nmap, Jinja2, PDFKit", "desc": "Automated scan, severity classification, remediation steps, PDF report."}, {"title": "Honeypot Deployment & Analysis", "tech": "Python, Cowrie, ELK Stack, Kibana", "desc": "SSH honeypot, attacker IP log, command analysis, Kibana dashboard."}, {"title": "Malware Sample Analyzer", "tech": "Python, YARA, VirusTotal API, Flask", "desc": "Static analysis, YARA rule matching, VT hash lookup, threat report."}, {"title": "Encrypted Chat Application", "tech": "Python, RSA/AES, Flask, Socket.io", "desc": "End-to-end encryption, key exchange, message integrity, secure login."}, {"title": "OSINT Reconnaissance Tool", "tech": "Python, Shodan API, WHOIS, Flask", "desc": "Domain/IP OSINT, subdomain enum, email harvesting, risk report."}],
    hard:   [{"title": "Web Application Penetration Testing Report", "tech": "Python, OWASP ZAP, Burp Suite, Markdown", "desc": "Automated scan on demo app, XSS/SQLi/CSRF findings, CVSS scoring, PDF."}, {"title": "SIEM Dashboard with Threat Detection", "tech": "Python, ELK Stack, Kibana, Wazuh", "desc": "Log ingestion from 5 sources, correlation rules, alert dashboard, incident response."}, {"title": "Zero-Day Vulnerability Research Report", "tech": "Python, GDB, Ghidra, Metasploit", "desc": "Binary analysis, exploit development, CVE documentation, responsible disclosure."}, {"title": "Blockchain-Based Digital Evidence System", "tech": "Python, Ethereum, Web3.py, Flask", "desc": "Evidence hash on blockchain, chain of custody, tamper-proof audit trail."}, {"title": "AI-Powered Intrusion Detection System", "tech": "Python, Scikit-learn, Kafka, ELK, Flask", "desc": "Network traffic ML classifier, real-time streaming detection, alert + block."}, {"title": "Red Team Simulation Report", "tech": "Python, Metasploit, Cobalt Strike, Nmap", "desc": "Full kill-chain simulation, lateral movement, data exfil demo, blue team debrief."}],
  },
  "software testing (qa)": {
    simple: [{"title": "Manual Test Plan for E-Commerce Site", "tech": "Excel, JIRA, TestRail", "desc": "Test cases for cart/checkout/payment, bug reports, severity classification."}, {"title": "Mobile App Manual Testing Report", "tech": "Android Studio, TestRail, JIRA", "desc": "Functional + UI test cases for Android app, defect log, regression checklist."}, {"title": "API Testing with Postman", "tech": "Postman, Newman, Excel", "desc": "REST API test collection, status/schema/response validation, HTML report."}, {"title": "Database Testing Report", "tech": "MySQL, Excel, JIRA", "desc": "Data integrity, constraint validation, stored procedure testing, test cases."}, {"title": "Regression Test Suite Document", "tech": "Excel, JIRA, TestRail", "desc": "Full regression suite, priority matrix, pass/fail tracking, release report."}],
    medium: [{"title": "Automated UI Testing with Selenium", "tech": "Python, Selenium, pytest, Allure", "desc": "Page Object Model, cross-browser test suite, CI integration, HTML report."}, {"title": "Performance Testing with JMeter", "tech": "Apache JMeter, Grafana, InfluxDB", "desc": "Load/stress/spike tests, throughput/latency metrics, bottleneck analysis."}, {"title": "Mobile Automation with Appium", "tech": "Python, Appium, pytest, Android", "desc": "Native Android app automation, gesture simulation, screenshot on failure."}, {"title": "BDD Testing with Cucumber", "tech": "Java, Cucumber, Selenium, Maven", "desc": "Gherkin feature files, step definitions, scenario outline, CI integration."}, {"title": "Security Testing Checklist & Report", "tech": "OWASP ZAP, Burp Suite, Excel", "desc": "OWASP Top 10 checks, XSS/SQLi/CSRF findings, severity rating, fix recommendations."}, {"title": "CI Testing Pipeline Setup", "tech": "Jenkins, GitHub Actions, Selenium, pytest", "desc": "Auto-trigger on PR, parallel test execution, Slack notification, test report."}],
    hard:   [{"title": "API Testing & Performance Dashboard", "tech": "Postman, k6, Grafana, Jenkins", "desc": "REST API test collection, load test with k6, performance dashboard, CI pipeline."}, {"title": "End-to-End Test Automation Framework", "tech": "Python, Playwright, pytest, Docker, CI", "desc": "Multi-browser E2E framework, parallel execution, Docker container, CI/CD."}, {"title": "Chaos Engineering Experiment", "tech": "Chaos Monkey, AWS, Grafana, Prometheus", "desc": "Failure injection on prod-like env, resilience validation, recovery SLA report."}, {"title": "AI-Assisted Test Case Generator", "tech": "Python, Gemini API, Selenium, FastAPI", "desc": "Input requirements \u2192 AI generates test cases \u2192 auto-execute \u2192 results dashboard."}, {"title": "Quality Metrics Dashboard", "tech": "Python, JIRA API, Plotly, Streamlit", "desc": "Defect density, test coverage, MTTR, release quality trend, exec report."}],
  },
  "app development": {
    simple: [{"title": "BMI Calculator App", "tech": "Flutter, Dart", "desc": "Height/weight input, BMI result, category color, history list, dark mode."}, {"title": "To-Do List App", "tech": "Flutter, Dart, SQLite", "desc": "Task CRUD, priority, due date, completion toggle, local storage."}, {"title": "Weather App", "tech": "Flutter, Dart, OpenWeather API", "desc": "Location-based weather, 5-day forecast, condition icons, unit toggle."}, {"title": "Currency Converter App", "tech": "Flutter, Dart, Exchange Rate API", "desc": "Real-time rates, swap currencies, conversion history, offline support."}, {"title": "Quiz App", "tech": "Flutter, Dart, SQLite", "desc": "Category/difficulty selector, timer, score tracker, results screen."}],
    medium: [{"title": "Expense Tracker App", "tech": "Flutter, Dart, SQLite, Charts", "desc": "Income/expense CRUD, category budget, monthly trend chart, PDF report."}, {"title": "Fitness Tracker App", "tech": "Flutter, Dart, SQLite, HealthKit", "desc": "Workout log, step counter, calorie burn, progress chart, goal setting."}, {"title": "Recipe App with Offline Support", "tech": "Flutter, Dart, SQLite, REST API", "desc": "Search recipes, save offline, step-by-step cook mode, shopping list."}, {"title": "Chat Application", "tech": "Flutter, Dart, Firebase", "desc": "Real-time messaging, read receipts, image sharing, push notifications."}, {"title": "News Reader App", "tech": "Flutter, Dart, News API, SQLite", "desc": "Category filter, bookmarks, offline reading, dark mode, share."}, {"title": "E-Commerce App", "tech": "Flutter, Dart, Firebase, Stripe", "desc": "Product listing, cart, wishlist, checkout, order tracking, reviews."}],
    hard:   [{"title": "Food Delivery App", "tech": "Flutter, Dart, Firebase, Google Maps", "desc": "Restaurant listing, live tracking, real-time orders, driver app, ratings."}, {"title": "Telemedicine App", "tech": "Flutter, Dart, Firebase, Agora SDK", "desc": "Doctor/patient portal, video consultation, prescription, appointment booking."}, {"title": "Social Media App", "tech": "Flutter, Dart, Firebase, Cloud Functions", "desc": "Feed, stories, real-time likes/comments, DM, notifications, explore page."}, {"title": "Ride-Sharing App", "tech": "Flutter, Dart, Firebase, Google Maps, Stripe", "desc": "Driver/rider app, live tracking, fare calculator, payment, ratings."}, {"title": "AI-Powered Personal Assistant App", "tech": "Flutter, Dart, Gemini API, Firebase", "desc": "Voice commands, calendar integration, smart reminders, task automation."}],
  },
  "ui/ux design": {
    simple: [{"title": "Personal Portfolio Redesign", "tech": "Figma", "desc": "Audit existing site, redesign hero + projects + contact, mobile-first layout."}, {"title": "Restaurant Menu App UI", "tech": "Figma, Adobe XD", "desc": "Menu browsing, item detail, cart flow, order confirmation screens."}, {"title": "Login & Onboarding Flow", "tech": "Figma", "desc": "5-screen onboarding, login/signup, error states, success animation."}, {"title": "Dashboard UI Design", "tech": "Figma, Tailwind CSS reference", "desc": "Admin dashboard, KPI cards, charts, sidebar nav, light/dark theme."}, {"title": "Mobile Banking App UI", "tech": "Figma", "desc": "Home, transfer, history, settings screens, accessibility compliant."}],
    medium: [{"title": "E-Commerce Mobile App Redesign", "tech": "Figma, Adobe XD, Maze", "desc": "Audit existing app UX, redesign product listing + cart flow, usability test."}, {"title": "Healthcare Patient Portal UX", "tech": "Figma, Maze, FigJam", "desc": "User research, journey map, hi-fi prototype, accessibility audit WCAG 2.1."}, {"title": "EdTech Platform UX Research", "tech": "Figma, Maze, Google Forms", "desc": "User interviews, affinity mapping, persona, lo-fi + hi-fi wireframes."}, {"title": "Food Delivery App Redesign", "tech": "Figma, Principle", "desc": "IA audit, user flow redesign, micro-interactions, prototype, usability test."}, {"title": "SaaS Dashboard Design System", "tech": "Figma, Tokens Studio", "desc": "Design tokens, component library, responsive grid, interactive prototype."}, {"title": "Accessibility Audit & Redesign", "tech": "Figma, Axe, WAVE", "desc": "WCAG audit of existing site, severity report, redesigned accessible components."}],
    hard:   [{"title": "AI Product Dashboard Design System", "tech": "Figma, Storybook, Tokens Studio", "desc": "Component library with design tokens, responsive grid, dark/light themes, docs."}, {"title": "Full App Design Sprint", "tech": "Figma, FigJam, Maze, Principle", "desc": "5-day sprint: problem framing, ideation, prototype, test, iteration report."}, {"title": "Design System for Fintech App", "tech": "Figma, Zeroheight, Tokens Studio", "desc": "Color/typography/spacing system, 50+ components, do/don't guidelines, Zeroheight docs."}, {"title": "AR/VR UX Prototype", "tech": "Figma, Spline, Unity (concept)", "desc": "Spatial UI design, 3D component concepts, interaction model, usability study."}],
  },
  "devops": {
    simple: [{"title": "Dockerize a Web Application", "tech": "Docker, Docker Compose, Nginx", "desc": "Dockerfile for Node.js app, docker-compose with DB, Nginx reverse proxy."}, {"title": "Linux Server Setup & Hardening", "tech": "Ubuntu, bash, ufw, fail2ban", "desc": "User management, SSH key auth, firewall rules, fail2ban, cron jobs."}, {"title": "Git Workflow Setup", "tech": "Git, GitHub, GitFlow", "desc": "Branch strategy, PR templates, commit conventions, tag releases, .gitignore."}, {"title": "Basic Monitoring with Prometheus", "tech": "Prometheus, Grafana, Node Exporter", "desc": "Node exporter setup, Prometheus scrape config, Grafana dashboard."}, {"title": "Nginx Load Balancer Setup", "tech": "Nginx, Docker, 3 Node.js instances", "desc": "Round-robin load balancing, health checks, upstream config, access logs."}],
    medium: [{"title": "CI/CD Pipeline with Jenkins", "tech": "Jenkins, Docker, GitHub, Maven", "desc": "Multibranch pipeline, build/test/deploy stages, Slack notification, rollback."}, {"title": "Kubernetes Cluster Setup", "tech": "Kubernetes, kubectl, Helm, Minikube", "desc": "Deployment/service/ingress, HPA, ConfigMaps, secrets, rolling update."}, {"title": "Infrastructure as Code with Terraform", "tech": "Terraform, AWS, HCL", "desc": "VPC + EC2 + RDS + S3 IaC, state management, modules, plan/apply workflow."}, {"title": "ELK Stack Log Management", "tech": "Elasticsearch, Logstash, Kibana, Filebeat", "desc": "Log ingestion from 3 sources, index patterns, Kibana dashboards, alerts."}, {"title": "Ansible Configuration Management", "tech": "Ansible, YAML, SSH, AWS EC2", "desc": "Playbooks for web server setup, idempotent tasks, inventory management."}, {"title": "GitOps with ArgoCD", "tech": "ArgoCD, Kubernetes, Helm, GitHub", "desc": "App deployment via Git, sync policies, rollback, multi-env management."}],
    hard:   [{"title": "Full DevOps Pipeline on AWS", "tech": "Jenkins, Docker, EKS, Terraform, Helm", "desc": "IaC infra, containerized app, CI/CD to K8s, monitoring, security scan."}, {"title": "Service Mesh with Istio", "tech": "Istio, Kubernetes, Kiali, Jaeger", "desc": "Traffic management, mTLS, circuit breaker, distributed tracing, dashboards."}, {"title": "Platform Engineering with Backstage", "tech": "Backstage, Kubernetes, GitHub, AWS", "desc": "Developer portal, software catalog, scaffolder templates, TechDocs."}, {"title": "SRE Runbook & SLO Dashboard", "tech": "Prometheus, Grafana, PagerDuty, Python", "desc": "SLI/SLO definition, error budget, alerting rules, runbook, incident review."}, {"title": "Multi-Cloud Deployment Strategy", "tech": "Terraform, AWS, GCP, Azure, Kubernetes", "desc": "Cloud-agnostic IaC, workload portability, cost comparison, failover demo."}],
  },
  "blockchain development": {
    simple: [{"title": "Hello World Smart Contract", "tech": "Solidity, Hardhat, Ethers.js", "desc": "Deploy ERC-20-like contract to testnet, interact via script, verify on Etherscan."}, {"title": "Cryptocurrency Wallet UI", "tech": "React.js, MetaMask, Ethers.js", "desc": "Connect wallet, display balance, send ETH, transaction history."}, {"title": "Token Airdrop Contract", "tech": "Solidity, Hardhat, OpenZeppelin", "desc": "ERC-20 token, whitelist airdrop, claim function, event logging."}, {"title": "Simple Voting DApp", "tech": "Solidity, Hardhat, React.js, Ethers.js", "desc": "Create proposals, cast votes, prevent double voting, result display."}],
    medium: [{"title": "NFT Minting Platform", "tech": "Solidity, IPFS, React.js, Ethers.js", "desc": "ERC-721 contract, IPFS metadata, mint UI, gallery, OpenSea compatible."}, {"title": "Decentralized Crowdfunding DApp", "tech": "Solidity, Hardhat, React.js, Ethers.js", "desc": "Campaign CRUD, ETH contributions, goal/deadline, refund mechanism."}, {"title": "Token Swap Interface", "tech": "Solidity, Uniswap V2, React.js, Ethers.js", "desc": "Token pair selection, price quote, slippage setting, swap execution."}, {"title": "Multi-Signature Wallet", "tech": "Solidity, Hardhat, React.js, Ethers.js", "desc": "N-of-M signature requirement, proposal/approve/execute flow, event log."}, {"title": "Supply Chain Tracker on Blockchain", "tech": "Solidity, Hardhat, React.js, IPFS", "desc": "Product lifecycle on-chain, QR scan to verify, tamper-proof history."}, {"title": "DAO Governance Contract", "tech": "Solidity, OpenZeppelin Governor, React.js", "desc": "Proposal creation, token-weighted voting, timelock execution, dashboard."}],
    hard:   [{"title": "DeFi Lending Protocol", "tech": "Solidity, Hardhat, Aave fork, React.js", "desc": "Deposit/borrow/repay/liquidate, interest rate model, price oracle, dashboard."}, {"title": "Cross-Chain Bridge", "tech": "Solidity, Hardhat, Chainlink CCIP, React.js", "desc": "Lock-and-mint bridge between 2 testnets, relayer, proof verification."}, {"title": "Decentralized Exchange (DEX)", "tech": "Solidity, AMM, Hardhat, React.js", "desc": "Liquidity pool, constant product formula, swap, LP token, fee distribution."}, {"title": "NFT Marketplace", "tech": "Solidity, IPFS, React.js, Ethers.js, Stripe", "desc": "List/buy/auction NFTs, royalties, featured drops, creator dashboard."}, {"title": "ZK-Proof Voting System", "tech": "Solidity, Circom, snarkjs, React.js", "desc": "Anonymous voting with ZK proof, nullifier to prevent double vote, verifier contract."}],
  },
  "hr assistant": {
    simple: [{"title": "Employee Onboarding Checklist App", "tech": "React.js, Node.js, MongoDB", "desc": "Onboarding task list, progress tracker, document upload, manager sign-off."}, {"title": "Leave Management System", "tech": "React.js, Node.js, PostgreSQL", "desc": "Leave request, approval workflow, balance tracker, calendar view, email alert."}, {"title": "Job Description Generator", "tech": "Python, Gemini API, Streamlit", "desc": "Role/level/skills input, AI generates JD, tone selector, export to Word."}, {"title": "Interview Scheduler Tool", "tech": "React.js, Node.js, Google Calendar API", "desc": "Candidate booking, panel availability, Zoom link gen, reminder email."}, {"title": "Employee Directory App", "tech": "React.js, Node.js, PostgreSQL", "desc": "Staff profiles, org chart, department filter, search, export CSV."}],
    medium: [{"title": "HR Chatbot for Policy Queries", "tech": "Python, Gemini API, LangChain, Streamlit", "desc": "Upload HR policy PDF, RAG chatbot answers employee queries, escalation flow."}, {"title": "Performance Review System", "tech": "React.js, Node.js, PostgreSQL, PDFKit", "desc": "360\u00b0 review form, rating aggregation, manager comments, PDF appraisal."}, {"title": "Recruitment Pipeline Tracker", "tech": "React.js, Node.js, PostgreSQL, Chart.js", "desc": "Job posting, applicant Kanban, stage tracking, source analytics, offer letter."}, {"title": "Payroll Calculator Dashboard", "tech": "React.js, Node.js, PostgreSQL, PDFKit", "desc": "CTC breakdown, deduction calculator, payslip generator, bulk processing."}, {"title": "Training & Development Tracker", "tech": "React.js, Node.js, MongoDB, Chart.js", "desc": "Course assignment, completion tracking, skill matrix, L&D budget dashboard."}],
    hard:   [{"title": "AI Resume Screening System", "tech": "Python, spaCy, BERT, FastAPI, React", "desc": "Bulk resume upload, JD matching, ranked shortlist, bias detection, report."}, {"title": "HR Analytics Dashboard", "tech": "Python, Pandas, Plotly, Scikit-learn, Streamlit", "desc": "Headcount forecast, attrition prediction, diversity metrics, workforce planning."}, {"title": "Compensation Benchmarking Tool", "tech": "Python, Pandas, Plotly, React, FastAPI", "desc": "Market salary data, pay equity analysis, band setting, pay gap report."}, {"title": "AI-Powered Succession Planning", "tech": "Python, Gemini API, React, FastAPI, PostgreSQL", "desc": "Talent mapping, role criticality, successor identification, development plan."}],
  },
};

function assignProject(domainName, existingCount) {
  const key = (domainName || '').toLowerCase().trim();
  const pool = DOMAIN_PROJECT_POOLS[key] || DOMAIN_PROJECT_POOLS['machine learning'];
  const idx = existingCount || 0;
  return [
    { stage: '🟢 Stage 1 — Simple', ...pool.simple[idx % pool.simple.length] },
    { stage: '🟡 Stage 2 — Medium', ...pool.medium[idx % pool.medium.length] },
    { stage: '🔴 Stage 3 — Hard',   ...pool.hard[idx % pool.hard.length] },
  ];
}

module.exports = { assignProject };
